[package]
name = "biotracker4"
version = "0.1.0"
authors = ["Max Breitenfeldt <git@mxbr.me>"]
edition = "2021"

[dependencies]
# egui
egui = { git = "https://github.com/emilk/egui" }
egui-wgpu = { git = "https://github.com/emilk/egui" }
eframe = { git = "https://github.com/emilk/egui", features=["wgpu"], default-features=false }

# gstreamer
glib = "0.15"
gst = { package = "gstreamer", version = "0.18" }
gst-app = { package = "gstreamer-app", version = "0.18" }
gst-video = { package = "gstreamer-video", version = "0.18" }

# other
anyhow = "1.0"
bytemuck = "1.12"
derive_more = "0.99"
rfd = "0.10"
shared_memory = "0.12"
zmq = "0.10"
serde = { version = "1.0", features=["derive"] }
serde_json = "1.0.87"
