[package]
name = "biotracker4"
version = "0.1.0"
authors = ["Max Breitenfeldt <git@mxbr.me>"]
edition = "2021"

[dependencies]
# egui
egui = { git = "https://github.com/emilk/egui" }
egui-wgpu = { git = "https://github.com/emilk/egui" }
eframe = { git = "https://github.com/emilk/egui", features=["wgpu"], default-features=false }

# other
anyhow = "1.0"
derive_more = "0.99"
rfd = "0.10"
shared_memory = "0.12"
zmq = "0.10"
serde = { version = "1.0", features=["derive"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
pathfinding = "3.0"
rand = "0.8"
cv = { package= "opencv", version="0.74" }
