[package]
name = "biotracker4"
version = "0.1.0"
authors = ["Max Breitenfeldt <git@mxbr.me>"]
edition = "2021"

[lib]
name = "libtracker"
path = "src/lib/lib.rs"

[dependencies]
# egui
egui = { git = "https://github.com/emilk/egui" }
egui-wgpu = { git = "https://github.com/emilk/egui" }
eframe = { git = "https://github.com/emilk/egui", features=["wgpu"], default-features=false }
rfd = "0.10"

# message protocol
zmq = "0.10"
shared_memory = "0.12"
prost = "0.11"
prost-types = "0.11"
bytes = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# other
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
pathfinding = "3.0"
rand = "0.8"
cv = { package= "opencv", version="0.75" }
pylon-cxx = { version = "0.3.4", optional = true }

[build-dependencies]
prost-build = "0.11"

[features]
pylon = ["dep:pylon-cxx"]
